[params]

# Auto translation configuration
# See: https://github.com/xnx3/translate/
[params.autoTranslate]
enable = true
# The translation service provider, ['client.edge', 'translate.service']
# See: https://translate.zvo.cn/43086.html
service = 'client.edge'
# List of language ID to translate to, e.g. ["english", "chinese_simplified", "chinese_traditional", ...]
# If not set, it will be translated to all languages
# See the full language list: https://api.translate.zvo.cn/language.json
languages = []
# Element IDs that needs to be ignored for translation, e.g. ["comment", ...]
ignoreID = []
# Class names that need to be ignored for translation, e.g. ["post-category", ...]
ignoreClass = []
# Tag names that need to be ignored for translation, e.g. ["title", ...]
ignoreTag = []
# Selectors that need to be ignored for translation, e.g. ["[data-adapters='projects'] .single-subtitle", ...]
ignoreSelector = []
# Texts that need to be ignored for translation, e.g. ["FixIt", "Lruihao", ...]
ignoreText = []
# Whether to detect the local language
detectLocalLanguage = false
# CDN of translate.js, e.g. https://cdn.jsdelivr.net/npm/i18n-jsautotranslate@latest
cdn = ""
# Whether to enable Enterprise-level translation channel
# If set to true, automatically switch to the best translation service
# See: https://github.com/hugo-fixit/cmpt-translate#enterprise
enterprise = false
