[params]
  # Auto translation configuration
  # See: https://github.com/xnx3/translate/
  [params.autoTranslate]
    enable = true
    # The translation service provider, ['client.edge', 'translate.service']
    # See: https://translate.zvo.cn/43086.html
    service = 'client.edge'
    # List of language ID to translate to, e.g. ["english", "chinese_simplified", "chinese_traditional", ...]
    # See the full language list: https://api.translate.zvo.cn/language.json
    languages = []
    # Class names that need to be ignored for translation.
    ignoreClass = []
    # Whether to detect the local language
    # If your site itself is multilingual in Hugo, it is not recommended to enable this feature!
    detectLocalLanguage = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.139.0"
